// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/qin8948050/kratos-layout/internal/biz"
	"github.com/qin8948050/kratos-layout/internal/conf"
	"github.com/qin8948050/kratos-layout/internal/data"
	"github.com/qin8948050/kratos-layout/internal/pkg/log"
	"github.com/qin8948050/kratos-layout/internal/pkg/trace"
	"github.com/qin8948050/kratos-layout/internal/server"
	"github.com/qin8948050/kratos-layout/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data) (*kratos.App, func(), error) {
	logger := log.NewLogger()
	string2 := trace.GetUrl()
	tracerProvider, err := trace.NewTracer(string2)
	if err != nil {
		return nil, nil, err
	}
	db, err := data.NewGormDB(confData, logger, tracerProvider)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(logger, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger, tracerProvider)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger, tracerProvider)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
